usage<-read.csv("11_08_2014usage.txt", header=TRUE, sep="|")
View(usage)
names(usage)
proper_date<-as.Date(usage$date, "%m/%d/%Y")
summary(proper_date)
new_usage<-cbind(usage,proper_date)
names(new_usage)
b4_jun<-as.Date("5/31/2014", "%m/%d/%Y")
aft_jun<-as.Date("7/1/2014", "%m/%d/%Y")
new_usage_oct<-subset(new_usage, proper_date > b4_jun & proper_date < aft_jun)
new_usage_oct<-subset(new_usage, proper_date > as.Date("5/31/2014", "%m/%d/%Y") & proper_date < as.Date("7/1/2014", "%m/%d/%Y"))
summary(new_usage_oct$proper_date)
